global:
  resolve_timeout: 1m
  slack_api_url: https://hooks.slack.com/services/mau-tau-aja-kamu

route:
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs: 
    - channel: '#alertmanager'
      icon_url: https://avatars3.githubusercontent.com/u/3380462
      send_resolved: true
      title: '{{ template "custom_title" . }}'
      text: '{{ template "custom_slack_message" . }}'

    
templates: 
  - /home/vagrant/alertmanager-0.15.2.linux-amd64/notifications.tmpl

