groups:
  - name: default
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          identifier: "{{ $labels.instance }}"
          description: "{{ $labels.job }} exporter job has been down for more than 5 minutes."
      - alert: NodeLowRootDisk
        expr: ((node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_free_bytes{mountpoint="/"} ) / node_filesystem_size_bytes{mountpoint="/"} * 100) > 75
        for: 1m
        labels:
          severity: critical
        annotations:
          identifier: "{{$labels.instance}}:"
          description: "{{$labels.job}}: Root disk usage is above 75% (current value is: {{ $value }})"          

